Repository DevOps-Nistagram-Organization/Nistagram-post-service, pull requests merged in 2021-09, with the labels that each got.

#2 #1 Initialized project
  .gitignore
  .mvn/wrapper/MavenWrapperDownloader.java
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/com/nistagram/post/PostApplication.java
  src/main/java/com/nistagram/post/client/UserClient.java
  src/main/java/com/nistagram/post/config/JwtAuthenticationEntryPoint.java
  src/main/java/com/nistagram/post/config/JwtRequestFilter.java
  src/main/java/com/nistagram/post/config/JwtTokenUtil.java
  src/main/java/com/nistagram/post/config/JwtUserDetailsService.java
  src/main/java/com/nistagram/post/config/WebSecurityConfig.java
  src/main/java/com/nistagram/post/model/dto/UserInfoDTO.java
  src/main/java/com/nistagram/post/model/entity/Authority.java
  src/main/java/com/nistagram/post/model/entity/Post.java
  src/main/java/com/nistagram/post/repository/PostRepository.java
  src/main/java/com/nistagram/post/service/UserService.java
  src/main/resources/application.yml
  src/main/resources/dataDev.sql
  src/test/java/com/nistagram/post/PostApplicationTests.java
Labels: backend

#24 Maven base Docker image
  .dockerignore
  Dockerfile.base
  README.md
Labels: devops

#25 Docker file Nistagram Post Microservice
  Dockerfile
  pom.xml
Labels: devops

#27 Release 1
  .dockerignore
  .github/workflows/ci-pr-develop-pipeline.yml
  .github/workflows/ci-push-develop-pipeline.yml
  .github/workflows/ci-push-main-pipeline.yml
  .gitignore
  .mvn/wrapper/MavenWrapperDownloader.java
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  Dockerfile
  Dockerfile.base
  README.md
  mvnw
  mvnw.cmd
  pom.xml
  publish-dockerhub.sh
  src/main/java/com/nistagram/post/PostApplication.java
  src/main/java/com/nistagram/post/client/UserClient.java
  src/main/java/com/nistagram/post/config/JwtAuthenticationEntryPoint.java
  src/main/java/com/nistagram/post/config/JwtRequestFilter.java
  src/main/java/com/nistagram/post/config/JwtTokenUtil.java
  src/main/java/com/nistagram/post/config/JwtUserDetailsService.java
  src/main/java/com/nistagram/post/config/WebSecurityConfig.java
  src/main/java/com/nistagram/post/controller/PostController.java
  src/main/java/com/nistagram/post/converter/CommentConverter.java
  src/main/java/com/nistagram/post/converter/PostConverter.java
  src/main/java/com/nistagram/post/model/dto/AddCommentDTO.java
  src/main/java/com/nistagram/post/model/dto/CommentDTO.java
  src/main/java/com/nistagram/post/model/dto/CreatePostDTO.java
  src/main/java/com/nistagram/post/model/dto/PostDTO.java
  src/main/java/com/nistagram/post/model/dto/PostIdWrapper.java
  src/main/java/com/nistagram/post/model/dto/UserInfoDTO.java
  src/main/java/com/nistagram/post/model/entity/Authority.java
  src/main/java/com/nistagram/post/model/entity/Comment.java
  src/main/java/com/nistagram/post/model/entity/Post.java
  src/main/java/com/nistagram/post/repository/CommentRepository.java
  src/main/java/com/nistagram/post/repository/PostRepository.java
  src/main/java/com/nistagram/post/service/PostService.java
  src/main/java/com/nistagram/post/service/UserService.java
  src/main/resources/application.yml
  src/main/resources/dataDev.sql
  src/test/java/com/nistagram/post/PostApplicationTests.java
Labels: backend, devops, frontend

#28 bugfix post#10
  publish-dockerhub.sh
Labels: bug

#36 post feign update
  pom.xml
  src/main/java/com/nistagram/post/PostApplication.java
  src/main/java/com/nistagram/post/client/UserClient.java
  src/main/resources/application-dev.properties
  src/main/resources/application-prod.properties
  src/main/resources/application-test.properties
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/main/resources/dataDev.sql
Labels: devops
